output "cluster_ids" {
  description = "AlloyDB cluster resource IDs keyed by cluster key."
  value       = { for k, c in google_alloydb_cluster.cluster : k => c.id }
}

output "cluster_names" {
  description = "AlloyDB cluster IDs (name field) keyed by cluster key."
  value       = { for k, c in google_alloydb_cluster.cluster : k => c.cluster_id }
}

output "cluster_uids" {
  description = "System-assigned UIDs for each cluster keyed by cluster key."
  value       = { for k, c in google_alloydb_cluster.cluster : k => c.uid }
}

output "primary_instance_ids" {
  description = "AlloyDB primary instance resource IDs keyed by cluster key."
  value       = { for k, i in google_alloydb_instance.primary : k => i.id }
}

output "primary_instance_names" {
  description = "AlloyDB primary instance names keyed by cluster key."
  value       = { for k, i in google_alloydb_instance.primary : k => i.instance_id }
}

output "primary_ip_addresses" {
  description = "Private IP addresses of primary instances keyed by cluster key."
  value       = { for k, i in google_alloydb_instance.primary : k => i.ip_address }
}

output "read_pool_ids" {
  description = "AlloyDB read pool instance resource IDs keyed by composite key (<cluster_key>--<instance_id>)."
  value       = { for k, rp in google_alloydb_instance.read_pool : k => rp.id }
}

output "read_pool_instance_names" {
  description = "AlloyDB read pool instance names keyed by composite key."
  value       = { for k, rp in google_alloydb_instance.read_pool : k => rp.instance_id }
}

output "read_pool_ip_addresses" {
  description = "Private IP addresses of read pool instances keyed by composite key."
  value       = { for k, rp in google_alloydb_instance.read_pool : k => rp.ip_address }
}

output "cluster_regions" {
  description = "Resolved region for each cluster keyed by cluster key."
  value       = { for k, c in local.clusters_map : k => c.region }
}

output "common_tags" {
  description = "Common governance labels generated by this module call."
  value       = local.common_tags
}
