output "notification_channel_ids" {
  description = "Notification channel resource IDs keyed by channel key."
  value       = { for k, c in google_monitoring_notification_channel.channel : k => c.id }
}

output "notification_channel_names" {
  description = "Notification channel resource names (full path) keyed by channel key. Use these to reference channels from alert policies outside this module."
  value       = { for k, c in google_monitoring_notification_channel.channel : k => c.name }
}

output "alert_policy_ids" {
  description = "Alert policy resource IDs keyed by policy key."
  value       = { for k, p in google_monitoring_alert_policy.policy : k => p.id }
}

output "alert_policy_names" {
  description = "Alert policy resource names (full path) keyed by policy key."
  value       = { for k, p in google_monitoring_alert_policy.policy : k => p.name }
}

output "uptime_check_ids" {
  description = "Uptime check resource IDs keyed by check key."
  value       = { for k, u in google_monitoring_uptime_check_config.uptime_check : k => u.id }
}

output "uptime_check_names" {
  description = "Uptime check resource names (full path) keyed by check key."
  value       = { for k, u in google_monitoring_uptime_check_config.uptime_check : k => u.name }
}

output "uptime_check_uptime_check_ids" {
  description = "Short uptime check IDs (used in metric filters and alert conditions) keyed by check key."
  value       = { for k, u in google_monitoring_uptime_check_config.uptime_check : k => u.uptime_check_id }
}

output "dashboard_ids" {
  description = "Dashboard resource IDs keyed by dashboard key."
  value       = { for k, d in google_monitoring_dashboard.dashboard : k => d.id }
}

output "common_labels" {
  description = "Common governance labels generated by this module call."
  value       = local.common_labels
}
