output "log_bucket_ids" {
  description = "Log bucket resource IDs keyed by bucket key."
  value       = { for k, b in google_logging_project_bucket_config.bucket : k => b.id }
}

output "log_bucket_names" {
  description = "Log bucket resource names (full path) keyed by bucket key."
  value       = { for k, b in google_logging_project_bucket_config.bucket : k => b.name }
}

output "log_sink_ids" {
  description = "Log sink resource IDs keyed by sink key."
  value       = { for k, s in google_logging_project_sink.sink : k => s.id }
}

output "log_sink_writer_identities" {
  description = "Per-sink writer service account identities keyed by sink key. Grant these the appropriate role on each destination resource."
  value       = { for k, s in google_logging_project_sink.sink : k => s.writer_identity }
}

output "log_exclusion_ids" {
  description = "Log exclusion resource IDs keyed by exclusion key."
  value       = { for k, e in google_logging_project_exclusion.exclusion : k => e.id }
}

output "log_metric_ids" {
  description = "Log-based metric resource IDs keyed by metric key."
  value       = { for k, m in google_logging_metric.metric : k => m.id }
}

output "log_metric_names" {
  description = "Log-based metric names as they appear in Cloud Monitoring (use in alert policy MQL filters) keyed by metric key."
  value       = { for k, m in google_logging_metric.metric : k => m.name }
}

output "common_labels" {
  description = "Common governance labels generated by this module call."
  value       = local.common_labels
}
