# outputs.tf

output "group_ids" {
  description = "Cloud Identity group resource names (IDs) keyed by group key."
  value       = { for k, g in google_cloud_identity_group.group : k => g.id }
}

output "group_names" {
  description = "Cloud Identity group display names keyed by group key."
  value       = { for k, g in google_cloud_identity_group.group : k => g.display_name }
}

output "group_emails" {
  description = "Group email addresses (GroupKey IDs) keyed by group key."
  value       = { for k, g in local.groups_map : k => g.email }
}

output "membership_ids" {
  description = "Membership resource names keyed by composite key (<group_key>--<member_key>)."
  value       = { for k, m in google_cloud_identity_group_membership.membership : k => m.id }
}

output "membership_group_keys" {
  description = "Parent group key for each membership, keyed by composite key."
  value       = { for k, m in local.memberships_map : k => m.group_key }
}

output "membership_member_emails" {
  description = "Member email addresses for each membership, keyed by composite key."
  value       = { for k, m in local.memberships_map : k => m.member_email }
}

output "customer_parent" {
  description = "Cloud Identity parent path used for all groups in this module call."
  value       = local.parent
}

output "common_tags" {
  description = "Common governance metadata generated by this module call."
  value       = local.common_tags
}
