output "autoscaler_ids" {
  description = "All autoscaler resource IDs keyed by autoscaler key."
  value       = module.gcp_autoscaling.autoscaler_ids
}

output "autoscaler_names" {
  description = "All autoscaler resource names keyed by autoscaler key."
  value       = module.gcp_autoscaling.autoscaler_names
}

output "autoscaler_self_links" {
  description = "All autoscaler self-links keyed by autoscaler key."
  value       = module.gcp_autoscaling.autoscaler_self_links
}

output "common_labels" {
  description = "Governance labels generated by this module call."
  value       = module.gcp_autoscaling.common_labels
}
