output "ha_gateway_ids" {
  description = "HA VPN gateway resource IDs keyed by gateway key."
  value       = { for k, g in google_compute_ha_vpn_gateway.ha_gateway : k => g.id }
}

output "ha_gateway_names" {
  description = "HA VPN gateway resource names keyed by gateway key."
  value       = { for k, g in google_compute_ha_vpn_gateway.ha_gateway : k => g.name }
}

output "ha_gateway_self_links" {
  description = "HA VPN gateway self-links keyed by gateway key."
  value       = { for k, g in google_compute_ha_vpn_gateway.ha_gateway : k => g.self_link }
}

output "ha_gateway_vpn_interfaces" {
  description = "Allocated external IP interfaces for each HA VPN gateway keyed by gateway key. Each entry contains a list of {id, ip_address} objects."
  value       = { for k, g in google_compute_ha_vpn_gateway.ha_gateway : k => g.vpn_interfaces }
}

output "peer_gateway_ids" {
  description = "External peer gateway resource IDs keyed by peer gateway key."
  value       = { for k, p in google_compute_external_vpn_gateway.peer_gateway : k => p.id }
}

output "peer_gateway_self_links" {
  description = "External peer gateway self-links keyed by peer gateway key."
  value       = { for k, p in google_compute_external_vpn_gateway.peer_gateway : k => p.self_link }
}

output "vpn_tunnel_ids" {
  description = "VPN tunnel resource IDs keyed by '<gateway_key>/<tunnel_key>'."
  value       = { for k, t in google_compute_vpn_tunnel.tunnel : k => t.id }
}

output "vpn_tunnel_names" {
  description = "VPN tunnel resource names keyed by '<gateway_key>/<tunnel_key>'."
  value       = { for k, t in google_compute_vpn_tunnel.tunnel : k => t.name }
}

output "vpn_tunnel_self_links" {
  description = "VPN tunnel self-links keyed by '<gateway_key>/<tunnel_key>'."
  value       = { for k, t in google_compute_vpn_tunnel.tunnel : k => t.self_link }
}

output "router_interface_names" {
  description = "Cloud Router interface names keyed by '<gateway_key>/<tunnel_key>'."
  value       = { for k, i in google_compute_router_interface.router_interface : k => i.name }
}

output "bgp_peer_names" {
  description = "BGP peer names keyed by '<gateway_key>/<tunnel_key>'."
  value       = { for k, p in google_compute_router_peer.bgp_peer : k => p.name }
}

output "common_labels" {
  description = "Governance labels generated by this module call."
  value       = local.common_labels
}
