# Map of folder input key to full folder resource name (folders/<id>).
output "folder_resource_names" {
  description = "Map of folders key to folder resource name (folders/<id>)."
  value       = local.folder_resource_names
}

# Map of folder input key to numeric folder ID.
output "folder_ids" {
  description = "Map of folders key to numeric folder ID."
  value       = { for k, v in local.folder_resource_names : k => replace(v, "folders/", "") }
}

# Map of folder input key to display name.
output "folder_display_names" {
  description = "Map of folders key to folder display name."
  value       = local.folder_display_names
}

# Map of folder IAM member key to resource ID.
output "folder_iam_member_ids" {
  description = "Map of folder IAM member key to resource ID."
  value       = { for k, v in google_folder_iam_member.member : k => v.id }
}

# Map of folder policy key to policy resource name.
output "folder_policy_names" {
  description = "Map of folder policy key to policy resource name."
  value       = { for k, v in google_org_policy_policy.policy : k => v.name }
}

# Map of log sink key to sink name.
output "folder_log_sink_names" {
  description = "Map of folder log sink key to sink name."
  value       = { for k, v in google_logging_folder_sink.sink : k => v.name }
}

# Map of log sink key to writer identity.
output "folder_log_sink_writer_identities" {
  description = "Map of folder log sink key to writer identity. Grant this principal write access to sink destinations."
  value       = { for k, v in google_logging_folder_sink.sink : k => v.writer_identity }
}

# Map of essential contact key to contact resource ID.
output "folder_essential_contact_ids" {
  description = "Map of folder essential contact key to contact resource ID."
  value       = { for k, v in google_essential_contacts_contact.contact : k => v.id }
}

# Common labels/tags generated by this module.
output "common_labels" {
  description = "Common labels map merged with created_date and managed_by."
  value       = local.common_labels
}
