output "ha_gateway_ids" {
  description = "HA VPN gateway resource IDs keyed by gateway key."
  value       = module.gcp_cloud_vpn.ha_gateway_ids
}

output "ha_gateway_names" {
  description = "HA VPN gateway resource names keyed by gateway key."
  value       = module.gcp_cloud_vpn.ha_gateway_names
}

output "ha_gateway_self_links" {
  description = "HA VPN gateway self-links keyed by gateway key."
  value       = module.gcp_cloud_vpn.ha_gateway_self_links
}

output "ha_gateway_vpn_interfaces" {
  description = "Allocated external IP interfaces keyed by gateway key. Provide these IPs to the peer device configuration."
  value       = module.gcp_cloud_vpn.ha_gateway_vpn_interfaces
}

output "peer_gateway_ids" {
  description = "External peer gateway IDs keyed by peer key."
  value       = module.gcp_cloud_vpn.peer_gateway_ids
}

output "vpn_tunnel_ids" {
  description = "VPN tunnel IDs keyed by '<gateway_key>/<tunnel_key>'."
  value       = module.gcp_cloud_vpn.vpn_tunnel_ids
}

output "vpn_tunnel_names" {
  description = "VPN tunnel names keyed by '<gateway_key>/<tunnel_key>'."
  value       = module.gcp_cloud_vpn.vpn_tunnel_names
}

output "router_interface_names" {
  description = "Cloud Router interface names keyed by '<gateway_key>/<tunnel_key>'."
  value       = module.gcp_cloud_vpn.router_interface_names
}

output "bgp_peer_names" {
  description = "BGP peer names keyed by '<gateway_key>/<tunnel_key>'."
  value       = module.gcp_cloud_vpn.bgp_peer_names
}

output "common_labels" {
  description = "Governance labels generated by this module call."
  value       = module.gcp_cloud_vpn.common_labels
}
