# ---------------------------------------------------------------------------
# Global External Application LB outputs
# ---------------------------------------------------------------------------
output "global_http_lb_ips" {
  description = "Global static IP addresses keyed by LB key. Empty string when reserve_ip_address = false (ephemeral IP is shown via forwarding rule)."
  value       = { for k, a in google_compute_global_address.global_http : k => a.address }
}

output "global_http_lb_forwarding_rule_ids" {
  description = "Global forwarding rule resource IDs keyed by LB key."
  value       = { for k, r in google_compute_global_forwarding_rule.global_http : k => r.id }
}

output "global_http_lb_forwarding_rule_ips" {
  description = "Effective IP addresses of global forwarding rules keyed by LB key (ephemeral or reserved)."
  value       = { for k, r in google_compute_global_forwarding_rule.global_http : k => r.ip_address }
}

output "global_http_backend_service_ids" {
  description = "Global backend service resource IDs keyed by LB key."
  value       = { for k, b in google_compute_backend_service.global_http : k => b.id }
}

output "global_http_url_map_ids" {
  description = "Global URL map resource IDs keyed by LB key."
  value       = { for k, u in google_compute_url_map.global_http : k => u.id }
}

# ---------------------------------------------------------------------------
# Regional Application LB outputs
# ---------------------------------------------------------------------------
output "regional_http_lb_ips" {
  description = "Regional static IP addresses keyed by LB key. Populated only when reserve_ip_address = true."
  value       = { for k, a in google_compute_address.regional_http : k => a.address }
}

output "regional_http_lb_forwarding_rule_ids" {
  description = "Regional forwarding rule resource IDs keyed by LB key."
  value       = { for k, r in google_compute_forwarding_rule.regional_http : k => r.id }
}

output "regional_http_lb_forwarding_rule_ips" {
  description = "Effective IP addresses of regional application LB forwarding rules keyed by LB key."
  value       = { for k, r in google_compute_forwarding_rule.regional_http : k => r.ip_address }
}

output "regional_http_backend_service_ids" {
  description = "Regional backend service resource IDs keyed by LB key."
  value       = { for k, b in google_compute_region_backend_service.regional_http : k => b.id }
}

# ---------------------------------------------------------------------------
# Regional External Passthrough NLB outputs
# ---------------------------------------------------------------------------
output "network_lb_ips" {
  description = "External static IP addresses for passthrough NLBs keyed by LB key."
  value       = { for k, a in google_compute_address.network_lb : k => a.address }
}

output "network_lb_forwarding_rule_ids" {
  description = "Passthrough NLB forwarding rule resource IDs keyed by LB key."
  value       = { for k, r in google_compute_forwarding_rule.network_lb : k => r.id }
}

output "network_lb_forwarding_rule_ips" {
  description = "Effective IP addresses of passthrough NLB forwarding rules keyed by LB key."
  value       = { for k, r in google_compute_forwarding_rule.network_lb : k => r.ip_address }
}

# ---------------------------------------------------------------------------
# Regional Internal Passthrough NLB outputs
# ---------------------------------------------------------------------------
output "internal_lb_forwarding_rule_ids" {
  description = "Internal NLB forwarding rule resource IDs keyed by LB key."
  value       = { for k, r in google_compute_forwarding_rule.internal_lb : k => r.id }
}

output "internal_lb_forwarding_rule_ips" {
  description = "Effective internal IP addresses of internal NLB forwarding rules keyed by LB key."
  value       = { for k, r in google_compute_forwarding_rule.internal_lb : k => r.ip_address }
}

# ---------------------------------------------------------------------------
# Common labels
# ---------------------------------------------------------------------------
output "common_labels" {
  description = "Governance labels generated by this module call."
  value       = local.common_labels
}
