# outputs.tf

# ---------------------------------------------------------------------------
# Step 1: Zone identity outputs.
# ---------------------------------------------------------------------------
output "zone_ids" {
  description = "DNS managed zone resource IDs keyed by zone key."
  value       = { for k, z in google_dns_managed_zone.zone : k => z.id }
}

output "zone_names" {
  description = "DNS managed zone resource names keyed by zone key."
  value       = { for k, z in google_dns_managed_zone.zone : k => z.name }
}

output "zone_dns_names" {
  description = "DNS name (domain) for each zone, keyed by zone key."
  value       = { for k, z in google_dns_managed_zone.zone : k => z.dns_name }
}

# ---------------------------------------------------------------------------
# Step 2: Name server delegation output for public zones.
# Use these to update NS records at your domain registrar.
# ---------------------------------------------------------------------------
output "zone_name_servers" {
  description = "Authoritative name servers assigned to each zone, keyed by zone key. Use for registrar delegation of public zones."
  value       = { for k, z in google_dns_managed_zone.zone : k => z.name_servers }
}

output "zone_visibility" {
  description = "Visibility of each zone (public or private), keyed by zone key."
  value       = { for k, z in google_dns_managed_zone.zone : k => z.visibility }
}

# ---------------------------------------------------------------------------
# Step 3: Record set outputs for both simple and routed records.
# ---------------------------------------------------------------------------
output "record_ids" {
  description = "DNS record set IDs keyed by composite key (<zone_key>--<record_key>)."
  value = merge(
    { for k, r in google_dns_record_set.simple : k => r.id },
    { for k, r in google_dns_record_set.routed : k => r.id }
  )
}

output "record_names" {
  description = "DNS record set names keyed by composite key (<zone_key>--<record_key>)."
  value = merge(
    { for k, r in google_dns_record_set.simple : k => r.name },
    { for k, r in google_dns_record_set.routed : k => r.name }
  )
}

# ---------------------------------------------------------------------------
# Step 4: Resolved project and common tags for downstream consumption.
# ---------------------------------------------------------------------------
output "zone_projects" {
  description = "Resolved project IDs for each zone, keyed by zone key."
  value       = { for k, z in local.zones_map : k => z.project_id }
}

output "common_tags" {
  description = "Common governance tags generated by this module call."
  value       = local.common_tags
}
