# Map of subnet input key to subnet self link.
output "subnet_self_links" {
  description = "Map of subnet key to subnet self link."
  value       = { for k, v in google_compute_subnetwork.subnet : k => v.self_link }
}

# Map of subnet input key to subnet name.
output "subnet_names" {
  description = "Map of subnet key to subnet name."
  value       = { for k, v in google_compute_subnetwork.subnet : k => v.name }
}

# Map of subnet input key to region.
output "subnet_regions" {
  description = "Map of subnet key to effective region."
  value       = { for k, v in google_compute_subnetwork.subnet : k => v.region }
}

# Map of subnet input key to CIDR range.
output "subnet_cidr_ranges" {
  description = "Map of subnet key to primary CIDR range."
  value       = { for k, v in google_compute_subnetwork.subnet : k => v.ip_cidr_range }
}

# Map of subnet input key to gateway address.
output "subnet_gateway_addresses" {
  description = "Map of subnet key to gateway address."
  value       = { for k, v in google_compute_subnetwork.subnet : k => v.gateway_address }
}

# Map of subnet input key to private Google access setting.
output "subnet_private_google_access" {
  description = "Map of subnet key to private Google access status."
  value       = { for k, v in google_compute_subnetwork.subnet : k => v.private_ip_google_access }
}

# Common labels/tags generated by this module.
output "common_labels" {
  description = "Common labels map merged with created_date and managed_by."
  value       = local.common_labels
}
