# Step 1: Expose instance IDs for both capacity models.
output "instance_ids" {
  description = "Cloud Spanner instance IDs keyed by instance key."
  value = merge(
    { for k, i in google_spanner_instance.processing_units : k => i.id },
    { for k, i in google_spanner_instance.processing_units_autoscaled : k => i.id },
    { for k, i in google_spanner_instance.nodes : k => i.id }
  )
}

# Step 2: Expose instance names for downstream references.
output "instance_names" {
  description = "Cloud Spanner instance names keyed by instance key."
  value = merge(
    { for k, i in google_spanner_instance.processing_units : k => i.name },
    { for k, i in google_spanner_instance.processing_units_autoscaled : k => i.name },
    { for k, i in google_spanner_instance.nodes : k => i.name }
  )
}

# Step 3: Expose instance configs for regional/multi-regional visibility.
output "instance_configs" {
  description = "Resolved instance config names keyed by instance key."
  value = merge(
    { for k, i in google_spanner_instance.processing_units : k => i.config },
    { for k, i in google_spanner_instance.processing_units_autoscaled : k => i.config },
    { for k, i in google_spanner_instance.nodes : k => i.config }
  )
}

# Step 4: Expose Spanner database IDs and names.
output "database_ids" {
  description = "Cloud Spanner database IDs keyed by <instance_key>--<database_key>."
  value       = { for k, d in google_spanner_database.database : k => d.id }
}

output "database_names" {
  description = "Cloud Spanner database names keyed by <instance_key>--<database_key>."
  value       = { for k, d in google_spanner_database.database : k => d.name }
}

# Step 5: Expose common governance labels generated by the module.
output "common_tags" {
  description = "Common governance tags generated by this module call."
  value       = local.common_tags
}
