output "log_bucket_ids" {
  description = "Log bucket resource IDs keyed by bucket key."
  value       = module.gcp_cloud_logging.log_bucket_ids
}

output "log_bucket_names" {
  description = "Log bucket full resource names keyed by bucket key."
  value       = module.gcp_cloud_logging.log_bucket_names
}

output "log_sink_ids" {
  description = "Log sink resource IDs keyed by sink key."
  value       = module.gcp_cloud_logging.log_sink_ids
}

output "log_sink_writer_identities" {
  description = "Per-sink writer service account identities keyed by sink key. Grant these the appropriate role on each destination resource."
  value       = module.gcp_cloud_logging.log_sink_writer_identities
}

output "log_exclusion_ids" {
  description = "Log exclusion resource IDs keyed by exclusion key."
  value       = module.gcp_cloud_logging.log_exclusion_ids
}

output "log_metric_ids" {
  description = "Log-based metric resource IDs keyed by metric key."
  value       = module.gcp_cloud_logging.log_metric_ids
}

output "log_metric_names" {
  description = "Log-based metric names (use in Cloud Monitoring alert filters) keyed by metric key."
  value       = module.gcp_cloud_logging.log_metric_names
}

output "common_labels" {
  description = "Governance labels generated by this module call."
  value       = module.gcp_cloud_logging.common_labels
}
