# outputs.tf

output "bucket_ids" {
  description = "Cloud Storage bucket resource IDs keyed by bucket key."
  value       = { for k, b in google_storage_bucket.bucket : k => b.id }
}

output "bucket_names" {
  description = "Bucket names keyed by bucket key."
  value       = { for k, b in google_storage_bucket.bucket : k => b.name }
}

output "bucket_urls" {
  description = "Bucket self-links (gs:// URLs) keyed by bucket key."
  value       = { for k, b in google_storage_bucket.bucket : k => b.url }
}

output "bucket_self_links" {
  description = "Full REST API self-link URIs for each bucket, keyed by bucket key."
  value       = { for k, b in google_storage_bucket.bucket : k => b.self_link }
}

output "bucket_locations" {
  description = "Resolved bucket locations keyed by bucket key."
  value       = { for k, b in local.buckets_map : k => b.location }
}

output "bucket_projects" {
  description = "Resolved project IDs for each bucket, keyed by bucket key."
  value       = { for k, b in local.buckets_map : k => b.project_id }
}

output "bucket_storage_classes" {
  description = "Storage class for each bucket, keyed by bucket key."
  value       = { for k, b in google_storage_bucket.bucket : k => b.storage_class }
}

output "versioning_enabled" {
  description = "Versioning state (true/false) for each bucket, keyed by bucket key."
  value       = { for k, b in local.buckets_map : k => b.versioning_enabled }
}

output "common_tags" {
  description = "Common governance tags generated by this module call."
  value       = local.common_tags
}
