output "autoscaler_ids" {
  description = "Autoscaler resource IDs keyed by autoscaler key (covers both regional and zonal)."
  value = merge(
    { for k, a in google_compute_region_autoscaler.regional : k => a.id },
    { for k, a in google_compute_autoscaler.zonal : k => a.id }
  )
}

output "autoscaler_names" {
  description = "Autoscaler resource names keyed by autoscaler key."
  value = merge(
    { for k, a in google_compute_region_autoscaler.regional : k => a.name },
    { for k, a in google_compute_autoscaler.zonal : k => a.name }
  )
}

output "autoscaler_self_links" {
  description = "Autoscaler self-links keyed by autoscaler key."
  value = merge(
    { for k, a in google_compute_region_autoscaler.regional : k => a.self_link },
    { for k, a in google_compute_autoscaler.zonal : k => a.self_link }
  )
}

output "regional_autoscaler_ids" {
  description = "Regional autoscaler resource IDs keyed by autoscaler key."
  value       = { for k, a in google_compute_region_autoscaler.regional : k => a.id }
}

output "zonal_autoscaler_ids" {
  description = "Zonal autoscaler resource IDs keyed by autoscaler key."
  value       = { for k, a in google_compute_autoscaler.zonal : k => a.id }
}

output "common_labels" {
  description = "Governance labels generated by this module call."
  value       = local.common_labels
}
