output "instance_ids" {
  description = "Cloud SQL instance resource IDs keyed by instance key."
  value       = { for k, i in google_sql_database_instance.instance : k => i.id }
}

output "instance_names" {
  description = "Cloud SQL instance names keyed by instance key."
  value       = { for k, i in google_sql_database_instance.instance : k => i.name }
}

output "instance_connection_names" {
  description = "Cloud SQL connection names (project:region:instance) keyed by instance key."
  value       = { for k, i in google_sql_database_instance.instance : k => i.connection_name }
}

output "instance_self_links" {
  description = "Full REST API self-links for each instance, keyed by instance key."
  value       = { for k, i in google_sql_database_instance.instance : k => i.self_link }
}

output "public_ip_addresses" {
  description = "Public IPv4 addresses for instances with ipv4_enabled = true, keyed by instance key."
  value       = { for k, i in google_sql_database_instance.instance : k => i.public_ip_address }
}

output "private_ip_addresses" {
  description = "Private IP addresses for instances on a VPC, keyed by instance key."
  value       = { for k, i in google_sql_database_instance.instance : k => i.private_ip_address }
}

output "database_ids" {
  description = "Cloud SQL database resource IDs keyed by composite key (<instance_key>--<db_name>)."
  value       = { for k, d in google_sql_database.database : k => d.id }
}

output "user_ids" {
  description = "Cloud SQL user resource IDs keyed by composite key (<instance_key>--<user_name>)."
  value       = { for k, u in google_sql_user.user : k => u.id }
}

output "instance_regions" {
  description = "Resolved region for each instance, keyed by instance key."
  value       = { for k, i in local.instances_map : k => i.region }
}

output "common_tags" {
  description = "Common governance tags generated by this module call."
  value       = local.common_tags
}
