# outputs.tf

output "nat_ids" {
  description = "Cloud NAT resource IDs keyed by NAT key."
  value = merge(
    { for k, n in google_compute_router_nat.nat_standard : k => n.id },
    { for k, n in google_compute_router_nat.nat_dynamic : k => n.id }
  )
}

output "nat_names" {
  description = "Cloud NAT names keyed by NAT key."
  value = merge(
    { for k, n in google_compute_router_nat.nat_standard : k => n.name },
    { for k, n in google_compute_router_nat.nat_dynamic : k => n.name }
  )
}

output "nat_router_names" {
  description = "Effective router names used by each NAT key."
  value = {
    for key, n in local.nats_map : key => (n.create_router ? google_compute_router.router[key].name : n.router)
  }
}

output "created_router_names" {
  description = "Routers created by this module, keyed by NAT key."
  value       = { for k, r in google_compute_router.router : k => r.name }
}

output "nat_regions" {
  description = "Resolved NAT regions keyed by NAT key."
  value       = { for k, n in local.nats_map : k => n.region }
}

output "nat_projects" {
  description = "Resolved NAT project IDs keyed by NAT key."
  value       = { for k, n in local.nats_map : k => n.project_id }
}

output "common_tags" {
  description = "Common tags metadata generated by this module call."
  value       = local.common_tags
}
